/**
 * PUNJAB UNIVERSITIES (outside Lahore)
 *
 * Rawalpindi, Faisalabad, Multan, Gujrat, Gujranwala, Sialkot, Sargodha,
 * Bahawalpur, Sahiwal, Dera Ghazi Khan and Rahim Yar Khan.
 */

import type { SeedUniversity } from "./types";

export const punjabUniversities: SeedUniversity[] = [
  // ------------------------------ RAWALPINDI -----------------------------
  {
    citySlug: "rawalpindi",
    name: "PMAS Arid Agriculture University Rawalpindi",
    shortName: "Arid Agriculture University",
    slug: "arid-agriculture-university",
    campus: "Shamsabad, Murree Road",
    website: "https://www.uaar.edu.pk",
    scale: "simple",
    established: 1994,
    sector: "Public",
    type: "Agriculture",
    notableFor: "Pakistan's specialist university for dryland (arid) agriculture.",
    summary:
      "Public university specialising in arid-zone agriculture, veterinary and food sciences.",
    detail:
      "Pir Mehr Ali Shah Arid Agriculture University Rawalpindi was granted university status in 1994, developing from a barani agricultural institute. It specialises in dryland farming, soil and water conservation, veterinary sciences and food technology, alongside management and computing faculties. Semester programmes use a four point scale.",
  },
  {
    citySlug: "rawalpindi",
    name: "Fatima Jinnah Women University",
    shortName: "FJWU",
    slug: "fatima-jinnah-women-university",
    campus: "The Mall, Rawalpindi",
    website: "https://www.fjwu.edu.pk",
    scale: "thirds",
    established: 1998,
    sector: "Public",
    type: "General",
    notableFor: "The first public women's university in Pakistan.",
    summary:
      "Public women's university offering arts, sciences, design and management programmes.",
    detail:
      "Fatima Jinnah Women University, established in 1998, was the first women's university in the public sector in Pakistan. It teaches social sciences, natural sciences, design, communication, computing and management on a semester system with a four point scale.",
  },
  {
    citySlug: "rawalpindi",
    name: "Rawalpindi Medical University",
    shortName: "RMU",
    slug: "rawalpindi-medical-university",
    campus: "Tipu Road, Rawalpindi",
    website: "https://www.rmur.edu.pk",
    scale: "simple",
    established: 1974,
    sector: "Public",
    type: "Medical",
    notableFor: "One of Punjab's major teaching hospitals and medical schools.",
    summary: "Public medical university with MBBS, postgraduate and allied health programmes.",
    detail:
      "Rawalpindi Medical College opened in 1974 and became Rawalpindi Medical University in 2017. It runs MBBS and a wide range of postgraduate medical programmes across three large allied teaching hospitals. Professional medical programmes commonly use annual examinations rather than semester GPA, so check which applies to your year.",
  },
  {
    citySlug: "rawalpindi",
    name: "National University of Medical Sciences",
    shortName: "NUMS",
    slug: "nums-rawalpindi",
    campus: "The Mall, Rawalpindi",
    website: "https://numspak.edu.pk",
    scale: "simple",
    established: 2015,
    sector: "Public",
    type: "Medical",
    notableFor: "Federally chartered university overseeing a network of medical colleges.",
    summary:
      "Public medical university covering medicine, dentistry, nursing and allied health sciences.",
    detail:
      "The National University of Medical Sciences was chartered in 2015 and oversees a national network of constituent and affiliated medical, dental and nursing institutions. It offers MBBS, BDS, allied health, nursing and postgraduate medical programmes.",
  },
  {
    citySlug: "rawalpindi",
    name: "Riphah International University Rawalpindi",
    shortName: "Riphah Rawalpindi",
    slug: "riphah-rawalpindi",
    campus: "Satellite Town Campus",
    website: "https://www.riphah.edu.pk",
    scale: "thirds",
    established: 2002,
    sector: "Private",
    type: "Health Sciences",
    notableFor: "Large private network strong in rehabilitation and health sciences.",
    summary:
      "Private university campus with health sciences, computing, engineering and management programmes.",
    detail:
      "Riphah International University was chartered in 2002 and its Rawalpindi campuses concentrate on health and rehabilitation sciences, medicine, dentistry, computing, engineering and management. Semester programmes use a four point scale with plus and minus grades.",
  },
  {
    citySlug: "rawalpindi",
    name: "Foundation University Rawalpindi Campus",
    shortName: "Foundation University",
    slug: "foundation-university-rawalpindi",
    campus: "New Lalazar, Rawalpindi",
    website: "https://fui.edu.pk",
    scale: "thirds",
    established: 2002,
    sector: "Private",
    type: "General",
    notableFor: "Private university with well-regarded medical and dental colleges.",
    summary:
      "Private university campus with medical, dental, computing and business programmes.",
    detail:
      "Foundation University was chartered in 2002, and its Rawalpindi campus hosts the medical and dental colleges alongside computing, engineering, psychology and management programmes. Semester-based programmes use a four point scale.",
  },

  // ------------------------------ FAISALABAD -----------------------------
  {
    citySlug: "faisalabad",
    name: "University of Agriculture Faisalabad",
    shortName: "UAF",
    slug: "university-of-agriculture-faisalabad",
    campus: "Main Campus, Jail Road",
    website: "https://web.uaf.edu.pk",
    scale: "simple",
    established: 1906,
    sector: "Public",
    type: "Agriculture",
    notableFor: "Pakistan's leading agricultural university and among its oldest institutions.",
    summary:
      "Leading public agricultural university with veterinary, food and engineering faculties.",
    detail:
      "The University of Agriculture Faisalabad traces its origins to 1906 and became a university in 1961. It is Pakistan's principal agricultural university, with faculties in agriculture, animal husbandry, veterinary science, food and nutrition, agricultural engineering and social sciences, and it runs sub-campuses across Punjab. Programmes use a four point scale.",
  },
  {
    citySlug: "faisalabad",
    name: "Government College University Faisalabad",
    shortName: "GCUF",
    slug: "gcu-faisalabad",
    campus: "Allama Iqbal Road Campus",
    website: "https://gcuf.edu.pk",
    scale: "simple",
    established: 1897,
    sector: "Public",
    type: "General",
    notableFor: "A historic college turned large general university for central Punjab.",
    summary:
      "Public university with programmes across sciences, arts, computing and management.",
    detail:
      "Government College University Faisalabad began as a college in 1897 and was granted university status in 2002. It now teaches natural sciences, social sciences, computing, management, languages and pharmacy, with several sub-campuses in the region. Semester programmes use a four point scale.",
  },
  {
    citySlug: "faisalabad",
    name: "National Textile University",
    shortName: "NTU",
    slug: "national-textile-university",
    campus: "Sheikhupura Road Campus",
    website: "https://www.ntu.edu.pk",
    scale: "halves",
    established: 1959,
    sector: "Public",
    type: "Engineering",
    notableFor: "Pakistan's only university dedicated to textile engineering and design.",
    summary:
      "Specialist public university for textile engineering, design and related sciences.",
    detail:
      "The National Textile University began in 1959 as a textile institute and is now Pakistan's specialist university for textile engineering, materials, garment manufacturing and textile design, alongside computing and management. Given the country's textile export industry, its graduates feed directly into that sector. Grading uses a four point scale.",
  },
  {
    citySlug: "faisalabad",
    name: "Faisalabad Medical University",
    shortName: "FMU",
    slug: "faisalabad-medical-university",
    campus: "Sargodha Road, Faisalabad",
    website: null,
    scale: "simple",
    established: 2017,
    sector: "Public",
    type: "Medical",
    notableFor: "Central Punjab's public medical university.",
    summary: "Public medical university offering MBBS and postgraduate medical programmes.",
    detail:
      "Faisalabad Medical University was established in 2017 from Punjab Medical College, which dates to 1973. It offers MBBS and postgraduate medical training through large allied teaching hospitals. Professional programmes may use annual examinations rather than semester GPA.",
  },
  {
    citySlug: "faisalabad",
    name: "The University of Faisalabad",
    shortName: "TUF",
    slug: "university-of-faisalabad",
    campus: "Sargodha Road Campus",
    website: "https://tuf.edu.pk",
    scale: "thirds",
    established: 2002,
    sector: "Private",
    type: "Health Sciences",
    notableFor: "Private university with a medical college and allied health programmes.",
    summary:
      "Private university with health sciences, engineering, management and media programmes.",
    detail:
      "The University of Faisalabad was chartered in 2002 and offers medicine, dentistry, pharmacy, allied health sciences, engineering, computing, management and media studies. Semester programmes use a four point scale with plus and minus grades.",
  },
  {
    citySlug: "faisalabad",
    name: "Government College Women University Faisalabad",
    shortName: "GCWUF",
    slug: "gcwu-faisalabad",
    campus: "Madina Town, Faisalabad",
    website: null,
    scale: "simple",
    established: 2012,
    sector: "Public",
    type: "General",
    notableFor: "Public women's university serving central Punjab.",
    summary:
      "Public women's university with sciences, arts, computing and management programmes.",
    detail:
      "Government College Women University Faisalabad was established in 2012 from a long-standing women's college. It teaches natural sciences, social sciences, computing, education and management on a semester system with a four point scale.",
  },
  {
    citySlug: "faisalabad",
    name: "NFC Institute of Engineering and Technology",
    shortName: "NFC IET",
    slug: "nfc-iet-faisalabad",
    campus: "Khanewal Road Campus",
    website: null,
    scale: "halves",
    established: 1982,
    sector: "Public",
    type: "Engineering",
    notableFor: "Engineering institute linked to the fertiliser industry.",
    summary: "Engineering institute with chemical, mechanical and electrical programmes.",
    detail:
      "The NFC Institute of Engineering and Technology offers undergraduate engineering in chemical, mechanical, electrical and civil disciplines, with historic links to Pakistan's fertiliser industry. Programmes are assessed on a semester system with a four point scale.",
  },

  // -------------------------------- MULTAN -------------------------------
  {
    citySlug: "multan",
    name: "Bahauddin Zakariya University",
    shortName: "BZU",
    slug: "bahauddin-zakariya-university",
    campus: "Bosan Road Campus",
    website: "https://www.bzu.edu.pk",
    scale: "simple",
    established: 1975,
    sector: "Public",
    type: "General",
    notableFor: "The principal university of southern Punjab.",
    summary:
      "The main public university of southern Punjab, with faculties across most disciplines.",
    detail:
      "Bahauddin Zakariya University was established in 1975 and is the principal public university of southern Punjab, with faculties in arts, sciences, engineering, agriculture, law, pharmacy and management, plus sub-campuses across the region. Semester programmes use a four point scale.",
  },
  {
    citySlug: "multan",
    name: "Nishtar Medical University",
    shortName: "Nishtar",
    slug: "nishtar-medical-university",
    campus: "Nishtar Road, Multan",
    website: null,
    scale: "simple",
    established: 1951,
    sector: "Public",
    type: "Medical",
    notableFor: "One of Pakistan's oldest medical colleges, serving southern Punjab.",
    summary: "Long-established public medical university serving southern Punjab.",
    detail:
      "Nishtar Medical College opened in 1951 and became a university in 2017. It is the main medical institution for southern Punjab, offering MBBS, dentistry, nursing and postgraduate medical programmes through a large teaching hospital.",
  },
  {
    citySlug: "multan",
    name: "MNS University of Agriculture Multan",
    shortName: "MNSUAM",
    slug: "mns-university-of-agriculture",
    campus: "Old Shujabad Road",
    website: "https://www.mnsuam.edu.pk",
    scale: "simple",
    established: 2012,
    sector: "Public",
    type: "Agriculture",
    notableFor: "Agricultural university serving Pakistan's cotton belt.",
    summary: "Specialist agricultural university for the cotton belt of southern Punjab.",
    detail:
      "Muhammad Nawaz Shareef University of Agriculture Multan was established in 2012 to serve southern Punjab's cotton and mango growing region, with departments in agronomy, plant breeding, horticulture, entomology and agricultural engineering.",
  },
  {
    citySlug: "multan",
    name: "MNS University of Engineering and Technology Multan",
    shortName: "MNS UET",
    slug: "mns-uet-multan",
    campus: "Bosan Road, Multan",
    website: null,
    scale: "halves",
    established: 2012,
    sector: "Public",
    type: "Engineering",
    notableFor: "Southern Punjab's dedicated engineering university.",
    summary:
      "Public engineering university with civil, electrical, mechanical and computer programmes.",
    detail:
      "Muhammad Nawaz Sharif University of Engineering and Technology Multan was established in 2012 to provide engineering education in southern Punjab, covering civil, electrical, mechanical, computer and architectural engineering on a semester system.",
  },
  {
    citySlug: "multan",
    name: "Women University Multan",
    shortName: "WUM",
    slug: "women-university-multan",
    campus: "Mattital Road, Multan",
    website: null,
    scale: "simple",
    established: 2013,
    sector: "Public",
    type: "General",
    notableFor: "Public women's university for southern Punjab.",
    summary: "Public women's university with sciences, arts and management programmes.",
    detail:
      "Women University Multan was established in 2013 and offers natural sciences, social sciences, education, computing and management programmes for women in southern Punjab, on a semester system with a four point scale.",
  },
  {
    citySlug: "multan",
    name: "Emerson University Multan",
    shortName: "Emerson",
    slug: "emerson-university",
    campus: "Bosan Road Campus",
    website: null,
    scale: "simple",
    established: 1920,
    sector: "Public",
    type: "General",
    notableFor: "Developed from Emerson College, one of Multan's oldest institutions.",
    summary: "Public university developed from one of Multan's oldest degree colleges.",
    detail:
      "Emerson University Multan grew out of Emerson College, founded in 1920, and was granted university status in 2021. It offers programmes across sciences, arts, computing, commerce and management on a semester system.",
  },

  // -------------------------------- GUJRAT -------------------------------
  {
    citySlug: "gujrat",
    name: "University of Gujrat",
    shortName: "UOG",
    slug: "university-of-gujrat",
    campus: "Hafiz Hayat Campus",
    website: "https://www.uog.edu.pk",
    // UOG does NOT follow any of the shared patterns: it has a B- but no A-,
    // C- or D+, and the points step down unevenly. Given its own table here so
    // that correcting it can never affect another university.
    scale: "simple",
    customGrades: [
      { grade: "A+", gradePoint: 4.0 },
      { grade: "A", gradePoint: 3.7 },
      { grade: "B+", gradePoint: 3.4 },
      { grade: "B", gradePoint: 3.0 },
      { grade: "B-", gradePoint: 2.5 },
      { grade: "C+", gradePoint: 2.0 },
      { grade: "C", gradePoint: 1.5 },
      { grade: "D", gradePoint: 1.0 },
      { grade: "F", gradePoint: 0.0 },
    ],
    verified: true,
    sourceNote:
      "Published University of Gujrat grading references, cross-checked against a second source for the grade letters and percentage bands, and confirmed by a student report.",
    established: 2004,
    sector: "Public",
    type: "General",
    notableFor: "The main university of the Gujrat region, with campuses across northern Punjab.",
    summary:
      "Public university covering engineering, sciences, arts, management and medicine.",
    detail:
      "The University of Gujrat was established in 2004 and has grown quickly into the principal university of northern Punjab's Gujrat region. Its Hafiz Hayat Campus hosts faculties in engineering and technology, computing, sciences, arts, management and social sciences, and the university runs sub-campuses in Sialkot and Narowal along with a constituent medical college. Semester programmes use a four point scale.",
  },
  {
    citySlug: "gujrat",
    name: "Nawaz Sharif Medical College",
    shortName: "NSMC Gujrat",
    slug: "nawaz-sharif-medical-college",
    campus: "University of Gujrat, Gujrat",
    website: null,
    // Grading left on the generic scale on purpose: MBBS here is examined by
    // UHS Lahore through annual professional examinations, not a semester GPA.
    scale: "simple",
    established: 2008,
    sector: "Public",
    type: "Medical",
    notableFor: "Gujrat's public medical college, affiliated with UHS Lahore for MBBS.",
    summary:
      "Public medical college in Gujrat offering MBBS, affiliated with UHS Lahore.",
    detail:
      "Nawaz Sharif Medical College was established in 2008 in Gujrat and was a constituent college of the University of Gujrat until 2022. It is now administered by the Punjab Specialized Healthcare and Medical Education Department, and its MBBS degree is awarded in affiliation with the University of Health Sciences, Lahore. MBBS is assessed through annual professional examinations rather than a semester GPA, so the calculator below will only match your results if your programme reports grades on a four point scale - check your result card first.",
  },
  {
    citySlug: "gujrat",
    name: "University of Lahore Gujrat Campus",
    shortName: "UOL Gujrat",
    slug: "uol-gujrat",
    campus: "Gujrat Campus",
    website: null,
    scale: "thirds",
    established: 2010,
    sector: "Private",
    type: "General",
    notableFor: "Private campus serving the Gujrat district.",
    summary:
      "Private university campus with business, computing and allied health programmes.",
    detail:
      "The University of Lahore's Gujrat campus brings the university's business, computing, allied health and social sciences programmes to the Gujrat district, following the same central grading rules as the main Lahore campus.",
  },

  // ------------------------------ GUJRANWALA -----------------------------
  {
    citySlug: "gujranwala",
    name: "University of the Punjab Gujranwala Campus",
    shortName: "PU Gujranwala",
    slug: "pu-gujranwala",
    campus: "Gujranwala Campus",
    website: null,
    scale: "tenths",
    established: 2012,
    sector: "Public",
    type: "General",
    notableFor: "Regional campus of Pakistan's oldest university.",
    summary:
      "Punjab University campus with business, computing, law and social sciences programmes.",
    detail:
      "The University of the Punjab's Gujranwala campus offers business administration, commerce, computing, law and social sciences programmes under the parent university's rules, using its 0.70/0.30 step grade table.",
  },
  {
    citySlug: "gujranwala",
    name: "GIFT University",
    shortName: "GIFT",
    slug: "gift-university",
    campus: "Main Campus, Gujranwala",
    website: "https://gift.edu.pk",
    scale: "thirds",
    established: 2002,
    sector: "Private",
    type: "Business",
    notableFor: "Gujranwala's main private university, strong in business education.",
    summary:
      "Private university with business, computing, engineering and social sciences programmes.",
    detail:
      "GIFT University was established in 2002 and chartered in 2008, making it Gujranwala's principal private university. It focuses on business administration, accounting and finance, computing, engineering and social sciences, on a semester system with a four point scale.",
  },
  {
    citySlug: "gujranwala",
    name: "Gujranwala Medical College",
    shortName: "GMC",
    slug: "gujranwala-medical-college",
    campus: "Gondlanwala Road",
    website: null,
    scale: "simple",
    established: 2010,
    sector: "Public",
    type: "Medical",
    notableFor: "The district's public medical college.",
    summary: "Public medical college offering MBBS with attached teaching hospitals.",
    detail:
      "Gujranwala Medical College was established in 2010 and offers MBBS with attached teaching hospitals serving the Gujranwala division. Medical programmes are normally assessed by professional examinations.",
  },
  {
    citySlug: "gujranwala",
    name: "UET Lahore Gujranwala Campus",
    shortName: "UET Gujranwala",
    slug: "uet-gujranwala",
    campus: "Gujranwala Campus",
    website: null,
    scale: "uet",
    established: 2002,
    sector: "Public",
    type: "Engineering",
    notableFor: "Engineering campus of UET Lahore serving the Gujranwala industrial belt.",
    summary:
      "UET campus with computer, electrical, mechanical and industrial engineering.",
    detail:
      "The University of Engineering and Technology Lahore's Gujranwala campus serves the surrounding industrial belt with computer, electrical, mechanical and industrial engineering programmes. It follows UET's grade table, where the lowest passing grade is D at 1.50 grade points.",
  },

  // -------------------------------- SIALKOT ------------------------------
  {
    citySlug: "sialkot",
    name: "University of Sialkot",
    shortName: "USKT",
    slug: "university-of-sialkot",
    campus: "Main Campus, Sialkot",
    website: "https://uskt.edu.pk",
    scale: "thirds",
    established: 2018,
    sector: "Private",
    type: "General",
    notableFor: "Sialkot's main private university, backed by the city's export industry.",
    summary:
      "Private university with business, engineering, computing and health sciences programmes.",
    detail:
      "The University of Sialkot was chartered in 2018 and serves a city built on sports goods, surgical instruments and leather exports. It offers business, computing, engineering, allied health sciences and social sciences on a semester system with a four point scale.",
  },
  {
    citySlug: "sialkot",
    name: "University of Gujrat Sialkot Sub-Campus",
    shortName: "UOG Sialkot",
    slug: "uog-sialkot",
    campus: "Sialkot Sub-Campus",
    website: null,
    scale: "simple",
    established: 2008,
    sector: "Public",
    type: "General",
    notableFor: "Public higher education for the Sialkot district.",
    summary:
      "Sub-campus of the University of Gujrat with business, computing and sciences programmes.",
    detail:
      "The University of Gujrat's Sialkot sub-campus brings public sector higher education to the Sialkot district, with programmes in business, computing, sciences and social sciences under the parent university's rules.",
  },
  {
    citySlug: "sialkot",
    name: "Government College Women University Sialkot",
    shortName: "GCWUS",
    slug: "gcwu-sialkot",
    campus: "Kutchery Road, Sialkot",
    website: null,
    scale: "simple",
    established: 2013,
    sector: "Public",
    type: "General",
    notableFor: "Public women's university for the Sialkot region.",
    summary: "Public women's university with sciences, arts and computing programmes.",
    detail:
      "Government College Women University Sialkot was established in 2013 from a long-standing women's college and offers sciences, social sciences, computing, education and management programmes on a semester system.",
  },
  {
    citySlug: "sialkot",
    name: "Khawaja Muhammad Safdar Medical College",
    shortName: "KMSMC",
    slug: "kmsmc-sialkot",
    campus: "Sialkot",
    website: null,
    scale: "simple",
    established: 2010,
    sector: "Public",
    type: "Medical",
    notableFor: "Sialkot's public medical college.",
    summary: "Public medical college offering MBBS with attached teaching hospitals.",
    detail:
      "Khawaja Muhammad Safdar Medical College was established in 2010 and offers MBBS with attached teaching hospitals serving the Sialkot district. Medical programmes are normally assessed by professional examinations rather than semester GPA.",
  },

  // ------------------------------- SARGODHA ------------------------------
  {
    citySlug: "sargodha",
    name: "University of Sargodha",
    shortName: "UOS",
    slug: "university-of-sargodha",
    campus: "University Road Campus",
    website: "https://su.edu.pk",
    scale: "simple",
    established: 2002,
    sector: "Public",
    type: "General",
    notableFor: "The principal university of central Punjab's Sargodha division.",
    summary:
      "Large public university with sciences, arts, pharmacy, engineering and medicine.",
    detail:
      "The University of Sargodha was granted university status in 2002, developing from a college founded in 1929. It is the principal university of the Sargodha division, with faculties in sciences, arts, pharmacy, engineering, agriculture and medicine, plus a constituent medical college. Semester programmes use a four point scale.",
  },
  {
    citySlug: "sargodha",
    name: "Sargodha Medical College",
    shortName: "SMC",
    slug: "sargodha-medical-college",
    campus: "University of Sargodha",
    website: null,
    scale: "simple",
    established: 2007,
    sector: "Public",
    type: "Medical",
    notableFor: "Constituent medical college of the University of Sargodha.",
    summary: "Public medical college offering MBBS within the University of Sargodha.",
    detail:
      "Sargodha Medical College is a constituent college of the University of Sargodha, established in 2007, offering MBBS with attached teaching hospitals serving the division.",
  },
  {
    citySlug: "sargodha",
    name: "University of Lahore Sargodha Campus",
    shortName: "UOL Sargodha",
    slug: "uol-sargodha",
    campus: "Sargodha Campus",
    website: null,
    scale: "thirds",
    established: 2010,
    sector: "Private",
    type: "General",
    notableFor: "Private campus serving the Sargodha division.",
    summary:
      "Private university campus with business, computing and allied health programmes.",
    detail:
      "The University of Lahore's Sargodha campus offers business, computing, allied health and social sciences programmes under the same central grading rules as its main Lahore campus.",
  },

  // ------------------------------ BAHAWALPUR -----------------------------
  {
    citySlug: "bahawalpur",
    name: "The Islamia University of Bahawalpur",
    shortName: "IUB",
    slug: "islamia-university-bahawalpur",
    campus: "Baghdad-ul-Jadeed Campus",
    website: "https://www.iub.edu.pk",
    scale: "simple",
    established: 1925,
    sector: "Public",
    type: "General",
    notableFor: "One of Pakistan's oldest seats of learning, founded as Jamia Abbasia.",
    summary:
      "Large public university with faculties across most disciplines in southern Punjab.",
    detail:
      "The Islamia University of Bahawalpur began in 1925 as Jamia Abbasia and became a modern university in 1975, making it one of Pakistan's oldest seats of learning. It is now a large institution with faculties in arts, sciences, engineering, agriculture, pharmacy, law, medicine and management across several campuses. Semester programmes use a four point scale.",
  },
  {
    citySlug: "bahawalpur",
    name: "Quaid-e-Azam Medical College Bahawalpur",
    shortName: "QAMC",
    slug: "quaid-e-azam-medical-college",
    campus: "Circular Road, Bahawalpur",
    website: null,
    scale: "simple",
    established: 1971,
    sector: "Public",
    type: "Medical",
    notableFor: "The Bahawalpur division's main public medical college.",
    summary: "Public medical college serving the Bahawalpur division.",
    detail:
      "Quaid-e-Azam Medical College was established in 1971 and is the main public medical institution for the Bahawalpur division, offering MBBS and postgraduate medical training through Bahawal Victoria Hospital.",
  },
  {
    citySlug: "bahawalpur",
    name: "Government Sadiq College Women University",
    shortName: "GSCWU",
    slug: "sadiq-college-women-university",
    campus: "Bahawalpur Campus",
    website: null,
    scale: "simple",
    established: 2013,
    sector: "Public",
    type: "General",
    notableFor: "Public women's university developed from a historic Bahawalpur college.",
    summary:
      "Public women's university offering sciences, arts, computing and management.",
    detail:
      "Government Sadiq College Women University Bahawalpur was established in 2013 from Government Sadiq College, which dates to 1942. It offers natural sciences, social sciences, computing, education and management programmes on a semester system.",
  },
  {
    citySlug: "bahawalpur",
    name: "Cholistan University of Veterinary and Animal Sciences",
    shortName: "CUVAS",
    slug: "cuvas-bahawalpur",
    campus: "Bahawalpur Campus",
    website: null,
    scale: "simple",
    established: 2014,
    sector: "Public",
    type: "Veterinary",
    notableFor: "Veterinary university serving the Cholistan livestock region.",
    summary:
      "Specialist public university for veterinary medicine and animal sciences.",
    detail:
      "Cholistan University of Veterinary and Animal Sciences was established in 2014 to serve the livestock economy of the Cholistan desert region, covering veterinary medicine, animal production, poultry and food sciences.",
  },

  // -------------------------------- SAHIWAL -----------------------------
  {
    citySlug: "sahiwal",
    name: "University of Sahiwal",
    shortName: "UOS Sahiwal",
    slug: "university-of-sahiwal",
    campus: "Noor Shah Road, Sahiwal",
    website: null,
    scale: "simple",
    established: 2016,
    sector: "Public",
    type: "General",
    notableFor: "The Sahiwal division's own public university.",
    summary:
      "Public university with sciences, commerce, computing and social sciences programmes.",
    detail:
      "The University of Sahiwal was established in 2016 to serve the Sahiwal division, teaching natural sciences, commerce, computing, education and social sciences on a semester system with a four point scale.",
  },
  {
    citySlug: "sahiwal",
    name: "COMSATS University Islamabad - Sahiwal Campus",
    shortName: "COMSATS Sahiwal",
    slug: "comsats-sahiwal",
    campus: "COMSATS Road, Sahiwal",
    website: null,
    scale: "thirds",
    established: 2006,
    sector: "Public",
    type: "IT",
    notableFor: "COMSATS campus serving central Punjab.",
    summary:
      "Campus of COMSATS University with computing, business and electrical engineering.",
    detail:
      "COMSATS University Islamabad's Sahiwal campus opened in 2006 and offers computer science, software engineering, electrical engineering, business and mathematics under the university's central grading rules.",
  },
  {
    citySlug: "sahiwal",
    name: "Sahiwal Medical College",
    shortName: "SLMC",
    slug: "sahiwal-medical-college",
    campus: "Farid Town, Sahiwal",
    website: null,
    scale: "simple",
    established: 2007,
    sector: "Public",
    type: "Medical",
    notableFor: "The division's public medical college.",
    summary: "Public medical college offering MBBS with an attached teaching hospital.",
    detail:
      "Sahiwal Medical College was established in 2007 and offers MBBS with an attached teaching hospital serving the Sahiwal division. Medical programmes are normally assessed by professional examinations.",
  },

  // --------------------------- DERA GHAZI KHAN ---------------------------
  {
    citySlug: "dera-ghazi-khan",
    name: "Ghazi University",
    shortName: "Ghazi University",
    slug: "ghazi-university",
    campus: "Dera Ghazi Khan",
    website: null,
    scale: "simple",
    established: 2012,
    sector: "Public",
    type: "General",
    notableFor: "The main public university of western Punjab.",
    summary:
      "Public university with sciences, agriculture, computing and social sciences programmes.",
    detail:
      "Ghazi University was established in 2012 in Dera Ghazi Khan to serve western Punjab, a largely rural region that previously had little local higher education. It teaches sciences, agriculture, computing, management and social sciences on a semester system.",
  },
  {
    citySlug: "dera-ghazi-khan",
    name: "Dera Ghazi Khan Medical College",
    shortName: "DGKMC",
    slug: "dg-khan-medical-college",
    campus: "Dera Ghazi Khan",
    website: null,
    scale: "simple",
    established: 2010,
    sector: "Public",
    type: "Medical",
    notableFor: "The region's public medical college.",
    summary: "Public medical college offering MBBS with attached teaching hospitals.",
    detail:
      "Dera Ghazi Khan Medical College was established in 2010 and offers MBBS with attached teaching hospitals serving a large rural region of western Punjab.",
  },
  {
    citySlug: "dera-ghazi-khan",
    name: "University of Education Dera Ghazi Khan Campus",
    shortName: "UE DG Khan",
    slug: "ue-dg-khan",
    campus: "Dera Ghazi Khan Campus",
    website: null,
    scale: "simple",
    established: 2002,
    sector: "Public",
    type: "Education",
    notableFor: "Teacher education campus for western Punjab.",
    summary:
      "Campus of the University of Education focused on teacher training and sciences.",
    detail:
      "The University of Education's Dera Ghazi Khan campus trains teachers for the region alongside programmes in sciences, computing and social sciences, following the parent university's semester rules.",
  },

  // --------------------------- RAHIM YAR KHAN ----------------------------
  {
    citySlug: "rahim-yar-khan",
    name: "Khwaja Fareed University of Engineering and Information Technology",
    shortName: "KFUEIT",
    slug: "kfueit",
    campus: "Abu Dhabi Road, Rahim Yar Khan",
    website: "https://www.kfueit.edu.pk",
    scale: "halves",
    established: 2014,
    sector: "Public",
    type: "Engineering",
    notableFor: "The far south of Punjab's engineering and IT university.",
    summary:
      "Public engineering and IT university serving the far south of Punjab.",
    detail:
      "Khwaja Fareed University of Engineering and Information Technology was established in 2014 in Rahim Yar Khan, bringing engineering and computing education to the far south of Punjab. It covers electrical, mechanical, civil and chemical engineering, computer science, management and sciences on a semester system.",
  },
  {
    citySlug: "rahim-yar-khan",
    name: "Sheikh Zayed Medical College",
    shortName: "SZMC",
    slug: "sheikh-zayed-medical-college",
    campus: "Rahim Yar Khan",
    website: null,
    scale: "simple",
    established: 2003,
    sector: "Public",
    type: "Medical",
    notableFor: "The district's public medical college and teaching hospital.",
    summary: "Public medical college offering MBBS with a large teaching hospital.",
    detail:
      "Sheikh Zayed Medical College was established in 2003 in Rahim Yar Khan and offers MBBS and postgraduate training through the Sheikh Zayed Hospital, serving the far south of Punjab.",
  },
  {
    citySlug: "rahim-yar-khan",
    name: "The Islamia University of Bahawalpur Rahim Yar Khan Campus",
    shortName: "IUB Rahim Yar Khan",
    slug: "iub-rahim-yar-khan",
    campus: "Rahim Yar Khan Campus",
    website: null,
    scale: "simple",
    established: 2005,
    sector: "Public",
    type: "General",
    notableFor: "Regional campus of The Islamia University of Bahawalpur.",
    summary:
      "University campus with sciences, computing, commerce and social sciences programmes.",
    detail:
      "The Islamia University of Bahawalpur's Rahim Yar Khan campus offers sciences, computing, commerce, education and social sciences programmes under the parent university's semester rules.",
  },
];
